try to fix workflow runs

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,22 +1,20 @@
 name: Test
 
 on:
-  workflow_run:
-    workflows: ["Build"]
-    types:
-      - completed
+  workflow_dispatch:
 
 jobs:
   Test:
-    if: ${{ github.event.workflow_run.conclusion == 'success' }}
     runs-on: ubuntu-latest
     container: wpilib/roborio-cross-ubuntu:2024-22.04
-
-    env:
-      GPR_USER: ${{ github.actor }}
-      GPR_KEY: ${{ secrets.GPR_KEY }}
-
     steps:
+      - name: Fail if Build workflow did not succeed
+        run: |
+          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
+            echo "Build workflow failed — failing Test workflow."
+            exit 1
+          fi
+
       - uses: actions/checkout@v4
 
       - name: Grant execute permission
@@ -32,7 +30,7 @@ jobs:
             --stacktrace
 
       - name: Upload test results
-        if: always() # ensures this runs even if tests fail
+        if: always()
         uses: actions/upload-artifact@v4
         with:
           name: test-results
